project:
  type: website
  output-dir: docs
  render:
    - inst/qmd/

website:
  title: "Daily Dashboard"
  navbar:
    left:
      - href: inst/qmd/index.qmd
        text: Home
      - href: inst/qmd/xkcd.qmd
        text: XKCD
      # - href: inst/qmd/treasury.qmd
      #   text: Treasury

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
