project:
  type: website
  output-dir: docs

website:
  title: "Daily Dashboard v2"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: xkcd_final.qmd
        text: XKCD
      # - href: treasury.qmd
      #   text: Treasury

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
