project:
  type: website
  output-dir: docs

website:
  title: "Daily Dashboard"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: dailydashboard.qmd
        text: Dashboard
      # - href: treasury.qmd
      #   text: Treasury

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
