# This file was generated by the {rix} R package v0.17.2 on 2025-11-26
# with following call:
# >rix(date = c(latest,
#  > "2025-11-03",
#  > "2025-11-01",
#  > "2025-08-18")[1],
#  > r_pkgs = r_pkgs,
#  > system_pkgs = system_pkgs,
#  > git_pkgs = gh_pkgs,
#  > local_r_pkgs = c("/Users/johngavin/docs_gh/claude_rix/random_walk/DESCRIPTION"),
#  > ide = c("positron",
#  > "rstudio")[1],
#  > project_path = ".",
#  > overwrite = TRUE,
#  > shell_hook = shell_hook,
#  > r_ver = "4.5.2")
# It uses the `rstats-on-nix` fork of `nixpkgs` which provides improved
# compatibility with older R versions and R packages for Linux/WSL and
# Apple Silicon computers.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/2025-11-10.tar.gz") { config.allowUnfree = true; };
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      air
      arrow
      autometric
      available
      covr
      crew
      dbplyr
      devtools
      dplyr
      DT
      duckdb
      furrr
      future
      future_apply
      gert
      ggdist
      ggplot2
      ggraph
      ggtext
      ggview
      gh
      gittargets
      here
      httptest
      igraph
      jsonlite
      keyring
      knitr
      logger
      lubridate
      mcptools
      mirai
      nanonext
      ollamar
      pins
      pkgdown
      plotly
      promises
      purrr
      quarto
      reticulate
      riingo
      rix
      rmarkdown
      rnaturalearth
      sf
      shiny
      shinydashboard
      shinyjs
      spelling
      stringr
      styler
      tarchetypes
      targets
      testthat
      tidyfinance
      tidymodels
      tidyquant
      tidyselect
      tidytuesdayR
      tidyverse
      units
      usethis
      withr;
  };
 
    btw = (pkgs.rPackages.buildRPackage {
      name = "btw";
      src = pkgs.fetchgit {
        url = "https://github.com/posit-dev/btw";
        rev = "c562575f01790b38a512ed199345aef695424e48";
        sha256 = "sha256-G12DBhn72wRJimyQTOd211HL9d7sClZ26qgRHO4JnXE=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages) 
          cli
          clipr
          dplyr
          ellmer
          fs
          jsonlite
          lifecycle
          mcptools
          pkgsearch
          rlang
          rmarkdown
          rstudioapi
          S7
          sessioninfo
          skimr
          tibble
          withr
          xml2
          #<- if (getRversion() < 4_3_0) S7;
          ;
      };
    });
     
  local_r_pkgs = [
    
  (pkgs.rPackages.buildRPackage {
    name = "docs";
    src = .//Users/johngavin/docs_gh/claude_rix/random_walk/DESCRIPTION;
    propagatedBuildInputs = builtins.attrValues {
     inherit (pkgs.rPackages) 
          logger
          ggplot2
          crew
          nanonext;
    };
  })

  ];
 
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      awscli2
      bc
      btop
      cacert
      claude-code
      cmdstan
      copilot-cli
      curlMinimal
      duckdb
      gemini-cli
      gettext
      gh
      git
      glibcLocales
      gnupg
      htop
      less
      libiconv
      nano
      nix
      nodejs
      ollama
      pandoc
      positron-bin
      quarto
      R
      texliveBasic
      toybox
      tree
      typst
      unzip
      which;
  };
  
  shell = pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    
    #<- buildInputs = [ btw rpkgs system_packages local_r_pkgs ];
    buildInputs = [ btw local_r_pkgs ] ++ rpkgs ++ system_packages;
    shellHook = "
# --- CRITICAL: Wrapper for Positron Terminal ---

# 1. Create the temporary wrapper script in a stable location
WRAPPER_DIR=\\$HOME/.config/positron
mkdir -p \\$WRAPPER_DIR
WRAPPER_SCRIPT=\\$WRAPPER_DIR/nix-terminal-wrapper.sh

# The derivation output path from nix-build is stored at the GC root symlink.
# We read the absolute path of the built environment from this symlink.
NIX_SHELL_PATH=$(readlink /Users/johngavin/docs_gh/rix.setup/nix-shell-root)
if [ -z "$NIX_SHELL_PATH" ]; then
    # Fallback to current $out if the symlink is missing (though it shouldn't be here)
    NIX_SHELL_PATH="$out" 
fi

cat > \\$WRAPPER_SCRIPT <<EOF
#!/bin/bash

printf '%s\n' 'Activating Nix shell environment...'

# 1. Source the Nix profile script from the *built derivation*.
# The path variable has been substituted here by the outer shell, so this line is a clean 'source /nix/store/...'
# This command is the CRITICAL step that sets PATH, man pages, and other environment variables.
# This is also a shell command, equivalent to 'source'
# Recommended fix for default.R (line ~204)
# This command is the CRITICAL step that sets PATH, man pages, and other environment variables.
true && source $NIX_SHELL_PATH/etc/profile.d/nix-shell.sh

# 2. Run environment activation hooks (if defined by Nix)
if declare -f __start_nix_shell_environment > /dev/null; then
    __start_nix_shell_environment
fi

# 3. Fix R Console Libraries: Ensure R finds the Nix-built packages.
# The R_LIB_PATH variable must still be escaped to prevent outer shell expansion here.
R_LIB_PATH=`sed -n '/R_LIBS_USER/{s/R_LIBS_USER=\"//; s/\"//; p; q}' $NIX_SHELL_PATH/etc/R/Rprofile.site`
export R_LIBS_USER=$R_LIB_PATH

# 4. Final confirmation before launch
printf '%s\n' 'Nix environment fully sourced.'

# 5. Ensure readline is configured for history navigation
# Create a temporary .bashrc for this session with readline settings
echo '# Nix shell readline configuration' > ~/.nix-shell-bashrc
echo 'set -o emacs' >> ~/.nix-shell-bashrc
echo 'bind "\\"\\\e[A\\": history-search-backward"' >> ~/.nix-shell-bashrc
echo 'bind "\\"\\\e[B\\": history-search-forward"' >> ~/.nix-shell-bashrc
echo 'bind "\\"\\\e[C\\": forward-char"' >> ~/.nix-shell-bashrc
echo 'bind "\\"\\\e[D\\": backward-char"' >> ~/.nix-shell-bashrc
echo '' >> ~/.nix-shell-bashrc
echo '# Source user bashrc if it exists' >> ~/.nix-shell-bashrc
echo 'if [ -f ~/.bashrc ]; then source ~/.bashrc; fi' >> ~/.nix-shell-bashrc

# 6. Launch the interactive shell with custom bashrc
# 'exec' replaces the current process with the new shell, making it the final terminal session.
exec /usr/bin/env bash --rcfile ~/.nix-shell-bashrc -i

EOF

# 2. Make the script executable and export the variable
chmod +x \\$WRAPPER_SCRIPT
export RSTUDIO_TERM_EXEC=\\$WRAPPER_SCRIPT

# IMPORTANT: Removed logic to modify ~/.zshrc or ~/.bashrc to prevent infinite recursion.

# === Other standard Nix shell setup ===
unset CI
printf '%s\\n' 'Setup complete'
printf 'Terminal wrapper: %s\\n' \\$RSTUDIO_TERM_EXEC
printf 'RSTUDIO_TERM_EXEC set to execute new shell with Nix environment.\\n'
# FIX: Correctly escaping $HOME here too.
date >> \\$HOME/.nix-session.log
";
  }; 
in
  {
    inherit pkgs shell;
  }
