#!/bin/bash
# Fixed version with proper GC root handling

# Define paths
PROJECT_PATH="/Users/johngavin/docs_gh/rix.setup"
GC_ROOT_PATH="$PROJECT_PATH/nix-shell-root"
NIX_FILE="$PROJECT_PATH/default.nix"

# Export environment variables BEFORE any Nix operations
export NIXPKGS_ALLOW_BROKEN=1 
export NIXPKGS_ALLOW_UNSUPPORTED_SYSTEM=1
export NIXPKGS_ALLOW_UNFREE=1

echo -e "\n=== STEP 1: Generate default.nix from default.R (if needed) ==="

if [ ! -f "$NIX_FILE" ] || [ "$NIX_FILE" -ot "$PROJECT_PATH/default.R" ]; then
    echo "Regenerating default.nix from default.R..."
    nix-shell \
        --pure \
        --keep PATH \
        --keep TMPDIR \
        --keep GITHUB_PAT \
        --keep NIXPKGS_ALLOW_UNSUPPORTED_SYSTEM \
        --expr "$(curl -sl https://raw.githubusercontent.com/b-rodrigues/rix/master/inst/extdata/default.nix)" \
        --command " \
            Rscript \
            --vanilla \
            $PROJECT_PATH/default.R \
            --args GITHUB_PAT=$GITHUB_PAT" \
        --cores 4 \
        --quiet
else
    echo "default.nix is up to date."
fi

echo -e "\n=== STEP 2: Build shell and create persistent GC root ==="

# Build the shell derivation and create GC root symlink atomically
# The -o flag creates the symlink AND protects from garbage collection
echo "cachix use rstats-on-nix # BEFORE nix-build"
cachix use rstats-on-nix

echo "Starting nix-build '$NIX_FILE' ..."
time nix-build "$NIX_FILE" \
    -A shell \
    -o "$GC_ROOT_PATH" \
    --cores 8 \
    --quiet

if [ ! -L "$GC_ROOT_PATH" ]; then
    echo "ERROR: Failed to build the Nix shell or create GC root at $GC_ROOT_PATH"
    exit 1
fi

STORE_PATH=$(readlink -f "$GC_ROOT_PATH")
echo "✓ SUCCESS: Persistent GC Root created"
echo "  Symlink: $GC_ROOT_PATH"
echo "  Points to: $STORE_PATH"
echo "  To allow garbage collection later, run: rm $GC_ROOT_PATH"

echo -e "\n=== STEP 3: Verify GC root is registered ==="
if nix-store --gc --print-roots | grep -q "$GC_ROOT_PATH"; then
    echo "✓ GC root is properly registered with Nix"
else
    echo "⚠ WARNING: GC root may not be properly registered"
fi



echo -e "\n=== STEP 4: Launch Positron and Enter Interactive Nix Shell (FINAL FIX for Darwin/macOS) ==="

# --- 4A: Resolve the GC Root Symlink to the actual Nix Store Path ---
if [ ! -L "$GC_ROOT_PATH" ]; then
    echo "ERROR: GC Root symlink not found at $GC_ROOT_PATH. Cannot proceed with fixed launch."
    exit 1
fi
# 1. Read the resolved path of the built Nix shell script from the GC root symlink
NIX_STORE_PATH=$(readlink "$GC_ROOT_PATH")

# 2. Prepare the environment file
# We strip the first 4 lines (warning banner) and save to a temp file to ensure clean sourcing.
ENV_SCRIPT="$TMPDIR/nix-env-$(date +%s).sh"
tail -n +5 "$NIX_STORE_PATH" > "$ENV_SCRIPT"

# 3. Source the environment in the CURRENT shell
echo "Activating Nix environment..."
USER_HOME="$HOME"
USER_SHELL="$SHELL"
# Define wrapper directory using USER_HOME (before sourcing Nix env)
WRAPPER_DIR="$USER_HOME/.config/positron"
mkdir -p "$WRAPPER_DIR"

source "$ENV_SCRIPT"

# Generate a clean environment file using export -p to properly handle multi-line variables
# We filter out BASH*, SHLVL, PWD, OLDPWD, and Nix internals
CLEAN_ENV_FILE="$WRAPPER_DIR/nix_env.sh"
rm -f "$CLEAN_ENV_FILE"
echo "Generating clean environment using export -p..."

# Use export -p which properly quotes all values, then filter and reformat
export -p | \
grep -vE "^declare -[a-zA-Z-]+ (BASH|SHLVL|PWD|OLDPWD|HOME|SHELL|TERM|USER|LOGNAME|DISPLAY|SSH_|Apple_|_|buildPhase|shellHook|builder|configureFlags|deps|doCheck|mesonFlags|name|nativeBuildInputs|out|outputs|patches|phases|preferLocalBuild|propagated|stdenv|strictDeps|system|TEMP|TMP|TMPDIR|NIX_BUILD)=" | \
sed 's/^declare -x /export /' | \
sed 's/^declare -[a-zA-Z-]* /export /' > "$CLEAN_ENV_FILE"

# Restore HOME and append system PATH (to fix locale, direnv, etc.)
export HOME="$USER_HOME"
export PATH="$PATH:$USER_PATH"

rm -f "$ENV_SCRIPT"

# 4. Run the shell hook (sets up aliases, etc.)
if [ -n "$shellHook" ]; then
    eval "$shellHook"
    
    # MANUALLY CREATE THE WRAPPER SCRIPT
    # shellHook fails to create it reliably due to escaping issues.
    WRAPPER_DIR="$HOME/.config/positron"
    mkdir -p "$WRAPPER_DIR"
    WRAPPER_FILE="$WRAPPER_DIR/nix-terminal-wrapper.sh"
    
    echo "Creating wrapper script at $WRAPPER_FILE..."
    cat > "$WRAPPER_FILE" <<'WRAPPER_EOF'
#!/bin/bash
# Wrapper script for Positron Terminal
# Generated by default.sh

# Source the Nix environment
if [ -n "$RIX_NIX_SHELL_ROOT" ] && [ -f "$RIX_NIX_SHELL_ROOT" ]; then
    # Source the environment (skipping first 4 lines)
    source <(tail -n +5 "$RIX_NIX_SHELL_ROOT")
fi

# Save the Nix PATH to restore it after user rc files run
export POSITRON_NIX_PATH="$PATH"
export POSITRON_NIX_ENV=1

# Create a custom rc file that preserves Nix PATH
CUSTOM_RC="$HOME/.config/positron/positron-shell-rc.sh"
cat > "$CUSTOM_RC" <<'RC_EOF'
# Source user's normal rc file
if [ -n "$BASH_VERSION" ]; then
    [ -f ~/.bashrc ] && source ~/.bashrc
elif [ -n "$ZSH_VERSION" ]; then
    [ -f ~/.zshrc ] && source ~/.zshrc
fi

# Restore Nix PATH priority (prepend Nix paths)
if [ -n "$POSITRON_NIX_PATH" ]; then
    export PATH="$POSITRON_NIX_PATH"
fi
RC_EOF

# Launch shell with custom rc file
if [ -n "$ZSH_VERSION" ] || [[ "$USER_SHELL" == *"zsh"* ]]; then
    # For zsh, use ZDOTDIR to point to custom rc
    # But this is complex, so instead just source the custom rc after zsh loads
    exec /bin/zsh -c "source $CUSTOM_RC; exec /bin/zsh -i"
else
    # For bash, use --rcfile
    exec /bin/bash --rcfile "$CUSTOM_RC" -i
fi
WRAPPER_EOF
    # Replace placeholders in wrapper
    sed -i '' "s|USER_SHELL|$USER_SHELL|g" "$WRAPPER_FILE"
    chmod +x "$WRAPPER_FILE"
fi

# Re-export critical variables
export NIXPKGS_ALLOW_BROKEN=1
export NIXPKGS_ALLOW_UNSUPPORTED_SYSTEM=1
export NIXPKGS_ALLOW_UNFREE=1
export GITHUB_PAT="$GITHUB_PAT"
# Fix log file creation
touch "$HOME/.nix-session.log" 2>/dev/null || true
export ANTHROPIC_API_KEY="$ANTHROPIC_API_KEY"
export TMPDIR="$TMPDIR"
# Export the GC root path so internal shells can source it
export RIX_NIX_SHELL_ROOT="$GC_ROOT_PATH"

echo "Debug: Git path: $(which git)"
echo "Debug: SSL_CERT_FILE: $NIX_SSL_CERT_FILE"

# 5. Launch Positron (ONLY from Nix environment)
if command -v positron &> /dev/null; then
    echo "Launching Positron from Nix environment..."
    # Log output to file for debugging
    echo "Debug: Launching Positron with --verbose"
    nohup positron --verbose > "/tmp/positron.log" 2>&1 &
else
    echo "⚠️  Positron not found in Nix environment PATH."
    echo "   PATH: $PATH"
fi

echo -e "\n=============================================="
echo "Entering INTERACTIVE Nix Shell"
echo "==============================================\n"

# 6. Replace current process with interactive shell
# Use -i flag to enable interactive mode with command history and readline
# We avoid -l (login shell) to prevent resetting PATH via ~/.zprofile / ~/.bash_profile
exec $SHELL -i

echo -e "\n=== Exited Nix shell ==="
echo "GC root still active at: $GC_ROOT_PATH"
echo "Environment remains protected from garbage collection."


